### ISSUE TITLE
0707 AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'

### ISSUE THREAD

**Issue by yeseong31** [yeseong31/kodeal-v2#10]
- 프로젝트 배포 후 서버를 실행할 때 **Internal Server Error** 문구가 뜨면서 화면이 출력되지 않음

```sh
2022-07-07T02:50:29.033875+00:00 app[web.1]: [2022-07-06 21:50:29 -0500] [10] [ERROR] Error handling request /favicon.ico
2022-07-07T02:50:29.033883+00:00 app[web.1]: Traceback (most recent call last):
2022-07-07T02:50:29.033884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
2022-07-07T02:50:29.033884+00:00 app[web.1]: self.handle_request(listener, req, client, addr)
2022-07-07T02:50:29.033885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2022-07-07T02:50:29.033885+00:00 app[web.1]: respiter = self.wsgi(environ, resp.start_response)
2022-07-07T02:50:29.033885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
2022-07-07T02:50:29.033886+00:00 app[web.1]: response = self.get_response(request)
2022-07-07T02:50:29.033886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/handlers/base.py", line 139, in get_response
2022-07-07T02:50:29.033887+00:00 app[web.1]: set_urlconf(settings.ROOT_URLCONF)
2022-07-07T02:50:29.033887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 88, in __getattr__
2022-07-07T02:50:29.033887+00:00 app[web.1]: val = getattr(self._wrapped, name)
2022-07-07T02:50:29.033888+00:00 app[web.1]: AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
2022-07-07T02:50:29.034071+00:00 app[web.1]: 10.1.82.128 - - [06/Jul/2022:21:50:29 -0500] "GET /favicon.ico HTTP/1.1" 500 0 "-" "-"
2022-07-07T02:50:29.034771+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=kodeal.herokuapp.com request_id=205cafd5-4286-4083-a3d3-ee8a80fa517a fwd="58.228.179.24" dyno=web.1 connect=0ms service=34ms status=500 bytes=244 protocol=https
```

**Comment by yeseong31** [comment]
- wsgi.py 파일의 내용을 다음과 같이 수정하여 해결함

```python
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.prod')  # config.settings에서 config.settings.prod로 수정

application = get_wsgi_application()
```

- 다만 서버 접속이 정상적인 것과는 별개로 **static 파일 접근이 전혀 되지 않아** 화면이 깔끔해 보이지 않으므로 수정이 필요함

**Comment by yeseong31** [comment]
- 로컬 서버 환경에서도 똑같은 현상이 발생하여 웹이 정상적으로 실행되지 않음

**Comment by yeseong31** [comment]
- local.py의 import 구문에 기본 환경 설정인 base.py에 대한 내용을 가져오는 문구가 없어서 발생하는 문제인 것으로 파악

```python
import dj_database_url
import openai

from .base import *  # local server 운영 시 반드시 필요
from . import my_settings
```
