### ISSUE TITLE
0707 Heroku 서버를 통한 마이그레이션 시 ERROR

### ISSUE THREAD

**Issue by yeseong31** [yeseong31/kodeal-v2#9]
- Heroku 세팅이 완료된 상태에서 `heroku run python manage.py migrate`를 통해 ClearDB에 마이그레이션을 시도할 때, 아래와 같이 ERROR 문구가 출력되면서 더 이상 진행이 되지 않는 문제가 있음

```
Running python manage.py migrate on ⬢ kodeal... up, run.6662 (Free)
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 108, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
```

- `set DJANGO_SETTINGS_MODULE=config.settings.prod` 명령어를 입력하여 서버 환경 파일을 읽을 수 있도록 했지만, 문제가 해결되지 않음

**Comment by yeseong31** [comment]
- 배포한 프로젝트 파일이 서버 환경 설정 파일을 읽지 못하여 발생한 것으로 보임

- `heroku run python manage.py migrate --settings=config.settings.prod` 명령어를 통해 서버 설정을 읽을 수 있도록 하여 마이그레이션을 수행하였고, 정상적으로 진행할 수 있었음
